### ISSUE TITLE
La aplicación no ha respondido con el /stats

### ISSUE THREAD

**Issue by javiermm8** [SrIzan10/vinci#7]
Al ejecutar el comando /stats en Vinci's Labs(porque no está en el de Mara Turing) me sale que la aplicación no ha respondido.

**Comment by SrIzan10** [comment]
aún no está en el servidor de producción, es decir, que aún no está listo

prueba hoy por la tarde, que probablemente ya estará!

**Comment by javiermm8** [comment]
Ok!
